### ISSUE TITLE
Can the language support Simplified Chinese?

### ISSUE THREAD

**Issue by fgr178707** [zly2006/reden-is-what-we-made#10]
![image](https://github.com/zly2006/reden-is-what-we-made/assets/109357981/05527107-3bcc-41ef-8886-976b0d5f01db)
Is the page brief not being considered at this time?

**Comment by zly2006** [comment]
忙不过来，谁想汉化开pr，我只做英语版

**Comment by fgr178707** [comment]
> 忙不过来，谁想汉化开pr，我只做英语版

好吧我等有空PR一下

**Comment by zly2006** [comment]
有一些字符串是硬编码的，需要改写为Text.translatable

期待你的pr
