### ISSUE TITLE
[Bug]: 语言切换简体中文显示英文

### ISSUE THREAD

**Issue by EshelGuo** [zly2006/reden-is-what-we-made#107]
### Please choose if applies:

- [ ] I'm currently working on a fix.

### Issue Description

加入Reden Mod ，启动游戏，语言切换为简体中文，游戏界面显示英文
移除Reden Mod，启动游戏， 语言切换为简体中文，游戏界面显示中文

### Reproduction

在1.20.4客户端添加reden以及前置mod，进入游戏后语言切换为简体中文即可复现

### Relevant log output (if applicable)

```Shell
https://pastebin.com/5YzS5L83
```

### Environment

- **Operating System**: Windows 10
- **Minecraft Version**: 1.20.4
- **Reden Mod Version (or commit number)**: reden-is-what-we-made-0.2.610-beta+1.20.4.fcd493c.gh-ci-595

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before
- [X] This is a bug report
- [x] This bug still exists
- [X] I enabled `redenDebug` in carpet or `debugLogger` options in malilib screen for my log

**Comment by zly2006** [comment]
你是指gui部分有的没翻译吗？请确认一下是哪个gui，目前80%的gui都是硬编码英文不支持i18n的

**Comment by EshelGuo** [comment]
是加入reden后，导致原版游戏主界面，设置界面等简体中文全变成英文，如图：https://github.com/EshelGuo/-/releases/download/v1.04/language_bug.png.jpeg

**Comment by zly2006** [comment]
无法在开发环境复现。建议移除除reden外所有模组试试，应该是兼容性有问题。可以通过二分法找找到底是谁冲突

**Comment by EshelGuo** [comment]
在移除所有不相关mod，只保留以下mod时依然有此问题:
fabric: 0.15.9
fabric API: fabric-api-0.96.11+1.20.4
carpet(前置): fabric-carpet-1.20.3-1.4.128+v231205
flk(前置): fabric-language-kotlin-1.10.19+kotlin.1.9.23
malilib(前置): malilib-fabric-1.20.4-0.18.1
owo(前置): owo-lib-0.12.6+1.20.3
reden: reden-is-what-we-made-0.2.610-beta+1.20.4.fcd493c.gh-ci-595

**Comment by zly2006** [comment]
无法复现。
<img width="966" alt="image" src="https://github.com/zly2006/reden-is-what-we-made/assets/66198935/b5b14244-0c6e-4597-a5dc-db7ab3c28acc">

**Comment by LukeChen-j** [comment]
我也遇到了同样的问题，模组菜单等模组显示的语言依然为设定的语言，但是游戏原版部分全部变成了英文。
比较神奇的是简中和文言有这个问题，繁中没有。
把模组删到只剩 Reden 以及前置之后问题依然存在

Windows 10 22H2
Java 17.0.9.8
Fabric 0.15.7
fabric-api-0.97.0+1.20.4
fabric-carpet-1.20.3-1.4.128+v231205
fabric-language-kotlin-1.10.19+kotlin.1.9.23
malilib-fabric-1.20.4-0.18.1
owo-lib-0.12.6+1.20.3
reden-is-what-we-made-0.2.611+aede6d0-beta+dev-ci-build.576

**Comment by zly2006** [comment]
> 我也遇到了同样的问题，模组菜单等模组显示的语言依然为设定的语言，但是游戏原版部分全部变成了英文。 比较神奇的是简中和文言有这个问题，繁中没有。 把模组删到只剩 Reden 以及前置之后问题依然存在
> 
> Windows 10 22H2 Java 17.0.9.8 Fabric 0.15.7 fabric-api-0.97.0+1.20.4 fabric-carpet-1.20.3-1.4.128+v231205 fabric-language-kotlin-1.10.19+kotlin.1.9.23 malilib-fabric-1.20.4-0.18.1 owo-lib-0.12.6+1.20.3 reden-is-what-we-made-0.2.611+aede6d0-beta+dev-ci-build.576

你好，能否测试一下最新版的情况？ https://github.com/zly2006/reden-is-what-we-made/actions/runs/8830332268

然后最好发一下完整日志

**Comment by LukeChen-j** [comment]
reden-is-what-we-made-0.2.624-dev+1.20.4.e80a2b6.gh-ci-607.jar 依然有这个问题
日志：https://1drv.ms/u/s!ArXJlVSLPl0Zgq8DRdYk9ATJUGUU-A?e=CWIENC

**Comment by zly2006** [comment]
[16:06:05] [Render thread/WARN]: Skipped language file: reden:lang/zh_cn.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 92 column 92 path $.reden.config.solidFaceShapePredicate.comment)
    [16:06:05] [Render thread/WARN]: Skipped language file: minecraft:lang/zh_cn.json (com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 294 column 7 path $.argument.entity.options.limit.too small)

所有的中文语言都被跳过了，确实有可能是reden的一个mixin导致的，但是原理尚不明晰

**Comment by zly2006** [comment]
我在开发环境仍然无法复现。请帮忙运行这个版本（至标题画面显示），然后发日志，感谢。

https://github.com/zly2006/reden-is-what-we-made/actions/runs/8866282983

**Comment by LukeChen-j** [comment]
reden-is-what-we-made-0.2.624-dev+lang-zh-cn.0b66ac0.gh-ci-608.jar 问题依然存在。
日志：https://1drv.ms/u/s!ArXJlVSLPl0Zgq8Ec_6UM8uFFyIVWA?e=v4dNiA

**Comment by zly2006** [comment]
继续测试：
https://github.com/zly2006/reden-is-what-we-made/actions/runs/8866392475/

**Comment by zly2006** [comment]
> 继续测试： https://github.com/zly2006/reden-is-what-we-made/actions/runs/8866392475/

私密马赛这个有bug，请用PR里的最新提交版本

**Comment by LukeChen-j** [comment]
reden-is-what-we-made-0.2.1-dev+HEAD.8bc3e16.gh-ci-138.jar：https://1drv.ms/u/s!ArXJlVSLPl0Zgq8FrmsImNbCXp5mmA?e=pGHwHm
reden-is-what-we-made-0.2.1-dev+HEAD.36a8f45.gh-ci-139.jar：https://1drv.ms/u/s!ArXJlVSLPl0Zgq8GaBNJsrrELnVS-A?e=ytzN6g

**Comment by zly2006** [comment]
请再试试： https://github.com/zly2006/reden-is-what-we-made/actions/runs/8866509176?pr=110

**Comment by LukeChen-j** [comment]
由于日志太多HMCL处理不过来没能成功导出。。。有什么推荐的导出日志的方法吗？

**Comment by LukeChen-j** [comment]
reden-is-what-we-made-0.2.1-dev+HEAD.172bc58.gh-ci-141.jar问题依然存在
https://1drv.ms/u/s!ArXJlVSLPl0Zgq8IVVy1PRDbUka8bQ?e=zFY1an

**Comment by zly2006** [comment]
这次正常了吗？

你可以直接打开游戏文件夹，找到logs，上传latest.log

**Comment by zly2006** [comment]
可以确认是utf8编码的问题了。
 https://github.com/zly2006/reden-is-what-we-made/actions/runs/8866594328/job/24344205934
这个应该能修好

**Comment by LukeChen-j** [comment]
问题确实解决了，不过貌似还有一些警告我不确定有没有关系：https://1drv.ms/u/s!ArXJlVSLPl0Zgq8Jx4zi_MgFva8GyA?e=gylgT2

**Comment by zly2006** [comment]
没关系的
