### ISSUE TITLE
1.21版本的bug

### ISSUE THREAD

**Issue by XiaoLLiu617** [zly2006/reden-is-what-we-made#121]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

**最新的1.21版本中有些bug**
1.下载个人数据无法下载在网页端显示如下
![0c698d679d7ce23f9ad2c504d2f6e709](https://github.com/zly2006/reden-is-what-we-made/assets/108166480/e51b64a6-b136-4e1d-a57f-9609ce9e08ff)
2.在游戏主页面中将鼠标悬浮在reden按钮不显示文字只有空的字符格
![image](https://github.com/zly2006/reden-is-what-we-made/assets/108166480/64435909-8eb8-4b72-84d2-48ec8141ab0e)
3.mod设置内无中文
4mod设置内显示的功能名称为项名称
![990be36cfb30d334f6372eef151c4540](https://github.com/zly2006/reden-is-what-we-made/assets/108166480/b90cc6a2-d26f-4b0f-933d-16388a18fdc2)

### 重现

1. 下载
2. 安装
3. 启动游戏
4. 就完了

### 环境

- **操作系统**：windows 11 24H2 insider preview
- **Minecraft 版本**：1.21
- **Reden Mod 版本（或 commit SHA）：**：0.2.675-dev1.21+10ed571

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在
- [X] 我在carpet中启用了`redenDebug`选项或在malilib配置中启用了`debugLogger`选项

**Comment by zly2006** [comment]
应该解决了，先关了
