### ISSUE TITLE
结构方块相关功能的整合与支持

### ISSUE THREAD

**Issue by VitaminC603** [zly2006/reden-is-what-we-made#19]
### 请选择：

- [ ] 我正在着手增加这个功能

### 描述您想要的解决方案

希望可以做到通过快捷键操控最近的结构方块进行保存/加载，如果保存/加载操作与其他指令一样可以被整合起来用一个快捷键连锁执行就更好了

### 描述您考虑过的替代方案

如果难以实现，可以考虑利用WE现有的选区，保存区域到文件，从文件加载区域的指令，并整合出可以快速调节参数的面板用于“自动生成”连续执行的一系列指令来达成类似的效果。

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by VitaminC603** [comment]
哦淦点错了，请自动无视“正在着手添加这个功能”

**Comment by zly2006** [comment]
关于快捷键我认为可以默认按下第一个键高亮选区，第二个键再执行，当然走masa

另一种就是不提示，Ctrl+L/Ctrl+S

选哪个键有建议吗

**Comment by zly2006** [comment]
> 哦淦点错了，请自动无视“正在着手添加这个功能”

没事，帮你改回来了

**Comment by Qubik65536** [comment]
> 哦淦点错了，请自动无视“正在着手添加这个功能”

可以点一下旁边方框的直接就变了😂

也可以用编辑功能
