### ISSUE TITLE
[Feature Request]: Add a feature that Rollback a single block instead of mutiple block.

### ISSUE THREAD

**Issue by Apricityx** [zly2006/reden-is-what-we-made#21]
### Please choose if applies:

- [ ] I'm currently working on adding this feature.

### Describe the solution you'd like

Setup a new Carpet rule to control if rollback a single block or mutiple block.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before

**Comment by zly2006** [comment]
Please make your description clearer.

A rule controlling instant changes? Or scheduled ticks? or BE? Or any other things?

**Comment by zly2006** [comment]
This may be a bug, check 65b1431

If you confirm this is a bug, please remove enhancement label and add bug label, then close this issue because it has been fixed.

**Comment by Apricityx** [comment]
I think this is a bug beacuse it won't rollback mutiple block anymore since I install the leatest version.
