### ISSUE TITLE
[功能请求]: 关于Undo对于block event和scheduled tick的支持

### ISSUE THREAD

**Issue by zly2006** [zly2006/reden-is-what-we-made#24]
### 请选择：

- [X] 我正在着手增加这个功能

### 描述您想要的解决方案

# What

undo目前只会滚实体nbt、方块实体nbt、方块状态，但是不支持计划刻和be。

这导致了：

+ 飞行器redo后不会继续运行
  - 手动更新并不保证有效
+ 快速的redo可能导致意外的更新

# Why：为什么难以解决

- 技术实现有困难，需要重构代码
- 内存占用（可能）
- 如何进行更新待讨论
- （重要） **操作后，计划刻造成了更新，这个更新记录到哪里？** 注意：操作造成的变化记录在undo record，撤销时生成一个redo record用于保存重做信息。重做后的计划刻造成了更新，算谁的？（这可以看作：由redo/undo产生的record）

# Discussion：如何进行更新

- 记录计划刻和be数据
  + 如何记录？
- 其他

**Comment by zly2006** [comment]
# 补充，Q&A

## Q：什么是undo/redo record？他们是怎么命名的？

A：undo record就是undo时需要应用的数据，记录了操作前的地图信息，redo record是redo要应用的数据，记录了undo这个操作本身带来变化之前的状态，也就是操作之后的状态

**Comment by Zaiyuyou** [comment]
### 希望添加支持的功能：
#### 支持回滚方块计划刻、pp更新、be更新，并且玩家可以在操作指令中添加 “-pp" "-be" 等字段来选择是否造成pp更新或者be更新的回滚
#### 支持在进行undo / redo 操作后自动冻结游戏时间，玩家在执行指令时添加 "-frz" 字段选择是否在执行操作后冻结游戏时间
#### 考虑到以上需要在指令中添加字段来自定义功能的要求，可能需要能够自动分割字符串并识别功能标签的代码块

**Comment by zly2006** [comment]
> # 希望添加支持的功能：
> ## 1. 支持回滚方块计划刻、pp更新、be更新，并且玩家可以在GUI设置中选择是否要在undo时恢复它们。
> ## 2.每一个玩家都有独立的undo / redo record index，用于指向自己触发的undo / redo record 中的元素，但具体undo / redo 时是仅对玩家对应的元素单独执行操作还是对玩家元素在record栈上所有元素进行操作需要进行讨论和测试

第一条可以用总结为: 在gui中选择是否更新，这将开发难度大大提高了，但确实是一种解决方案，我们应该追求更好开发一点的方式

第二条请发一个独立的建议，请单独发一个issue

**Comment by zly2006** [comment]
考虑：

移除undo处的所有计划刻，但不对计划刻进行添加和回滚
