### ISSUE TITLE
🐞 Two mobs respawned when reverting the action of killing one with TNT

### ISSUE THREAD

**Issue by Qubik65536** [zly2006/reden-is-what-we-made#3]
## Description

If the player kills one mob (e.g. villager, creeper) using TNT then uses `ctrl+z` to revert, two mobs will be respawned.

## To Reproduce

1. Spawn a mob
2. Place a TNT
3. Activate the TNT
4. The TNT kills the mob
5. Use `ctrl+z` to revert
6. (BUG) There's two mob

## Expected Behavior

Only one mob should be respawned.

## Version Information

(In IntelliJ IDEA development environment)
Reden Version: d4ef4c9ab06fce935b77740818e720d11993a056
Minecraft: 1.20.1
Fabric Loader: 0.14.21
Java: Temurin-17.0.6+10 (build 17.0.6+10)

## Note

I cannot stably reproduce this.

## Log

Will add once after I reproduced this bug again.

## Screenshots/Screen Recordings

Will add once after I reproduced this bug again.

**Comment by zly2006** [comment]
I 've found the reason, logs and screenshots are not needed,

**Comment by Qubik65536** [comment]
Can confirm it's fixed.
