### ISSUE TITLE
[Others]: Changing license to LGPL-3.0

### ISSUE THREAD

**Issue by wafarm** [zly2006/reden-is-what-we-made#32]
### Description

Currently, our mod is using GPL-3.0 as the license. But due to the incompatibility between the license and Minecraft as is pointed out in [GPL's faq](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins), we are considering changing the license to LGPL-3.0, which is compatible with Minecraft.

We value the input and perspectives of our contributors. Please share your thoughts on this proposed license change.. You can either leave a comment below or reply with emoji. We will only perform the change if all our contributors agree on this.

**Comment by wafarm** [comment]
@zly2006 @onion108 @lovexyn0827 @Cubik65536 We need your feedback.

**Comment by Qubik65536** [comment]
My opinion would be try anything to adapt the correct license and to follow it as much as possible.
