### ISSUE TITLE
[Feature Request]: Minecraft coroutine: MineRoutine

### ISSUE THREAD

**Issue by zly2006** [zly2006/reden-is-what-we-made#36]
### Please choose if applies:

- [X] I'm currently working on adding this feature.

### Describe the solution you'd like

# Introduction

MineRoutine aims to bring coroutine features to Minecraft ticking. Thus, you can jump out of the normal tick processing and do something else like network, so it can be a foundation of breakpoint features.

MineRoutine is a non-preemptive and stackless coroutine. So we should record the tick process ourselves in order to continue ticking.

# How to?

I considered two ways to implement this feature.

1. By adding conditions to vanilla ticking, for example, if we are ticking a certain entity, then just disallow chunk ticking, scheduled ticks ticking, and other entities, etc. This can be compatible with other mods as much as possible.
2. By writing another tick system, this way can make it much easier to implement this feature, but it may be incompatible with nearly all mods that modified tick. Meanwhile, in different versions we must repeat the same code many times, making it hard to maintain.

Feel free to share your opinion! Please think of what difficulties this new feature may face, or other suggestions about it.

### Anything else?

@wafarm @Cubik65536 your opinion plz~

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before

**Comment by eav-eav-eav** [comment]
For the first appoach, you mean, by adding a condition to a certain tick stage, this stage can be manually controlled whether ticks or not?

**Comment by zly2006** [comment]
> For the first appoach, you mean, by adding a condition to a certain tick stage, this stage can be manually controlled whether ticks or not?

I mean, by adding a condition, we can cancel all other tick stages, so only a certain tick stage will be processed.

Because it use vanilla methods, it will be more compatible with other mods.

In fact, this is what carpet mod doing---it cancelled all tick stages except NU is game was frozen.

**Comment by eav-eav-eav** [comment]
```java
// Normal, could be from entity, block, world...
void tick() {
    logic();
}

// Patched
void tick() {
    if (TickStage.currentStages().contains(this.stage())) {
        logic();
    }
}
```
Like this?

**Comment by zly2006** [comment]
> ```java
> // Normal, could be from entity, block, world...
> void tick() {
>     logic();
> }
> 
> // Patched
> void tick() {
>     if (TickStage.currentStages().contains(this.stage())) {
>         logic();
>     }
> }
> ```
> 
> Like this?

yes, and please note that although I said "stage", but in fact we plan to support smaller events than a stage like NU/NTE, such as ticks of a certain entity.

**Comment by zly2006** [comment]
Maybe we can use asm to modify bytecode directly instead of Mixin so that we can add some goto instructions 🤔

**Comment by eav-eav-eav** [comment]
> Maybe we can use asm to modify bytecode directly instead of Mixin so that we can add some goto instructions 🤔

That may be problematic. Mixin should take care of this.

**Comment by eav-eav-eav** [comment]
LGTM, but how is this related to coroutine? I mean, it's more of a in-game tool, while coroutine is for development.

**Comment by zly2006** [comment]
> to modify bytecode directly instead of Mixin so that we can add some goto instructions

But it does make it easy to skip normal tick. Only in a few situations, we can add a return instruction to skip (which is supported by mixin), or we must use redirect or overwrite and it seems like just repeating minecraft's code.

**Comment by eav-eav-eav** [comment]
Right...it's an issue for larger pieces. But I still doubt the stability of inserting instructions manually. Maybe worth a try.

**Comment by zly2006** [comment]
> LGTM, but how is this related to coroutine? I mean, it's more of a in-game tool, while coroutine is for development.

Currently, this feature is planning, and although coroutine can be useful in many situations, it does not mean any performance improvement or other significant improvement to the game experience. So idk if it is really useful to other mods except reden.

If you want to participate in this project now, maybe discussing interfaces and structure designing would be a good idea.

**Comment by eav-eav-eav** [comment]
The only thing I could imagine is, with this system, some logic within reden could be written in coroutine style. For example:

```kotlin
suspend fun test() {
    yield() // Suspends until the stage (or this Tickable) continues ticking
    println("Resumed!")
}
```

**Comment by zly2006** [comment]
what's more, if we finally decide to use the first plan, it may reduce the performance.

certainly, It would be better if this feature could make it easier to improve mc's performance, as coroutines often be used to do, so maybe we should have more discussion about that.

**Comment by zly2006** [comment]
> The only thing I could imagine is, with this system, some logic within reden could be written in coroutine style. For example:
> 
> ```kotlin
> suspend fun test() {
>     yield() // Suspends until the stage (or this Tickable) continues ticking
>     println("Resumed!")
> }
> ```

Yes, that is the best choice if yield can really yield the thread, to reduce the resource usage.

But i think it is too hard to implement, nearly impossible.

**Comment by eav-eav-eav** [comment]
> Yes, that is the best choice if yield can really yield the thread, to reduce the resource usage.
> 
> But i think it is too hard to implement, nearly impossible.

Not that hard actually. I'm working on similar stuff so already have something in mind. Just a bunch of `@Inject` into those Tickables and here we go.

Of course it does yield the main thread, otherwise it's not coroutine anymore lol.

**Comment by zly2006** [comment]
My plan is to record something like call stack with many frames, each frame has many tasks, and yield for main thread is to run other stacks (provided by network or other mod), resume is to runtime to run the main thread tasks.

**Comment by eav-eav-eav** [comment]
Sad I'm buzy recently, I'd write a sample soon.

**Comment by zly2006** [comment]
but how to divide a vanilla method into many tasks? that is what this issue is talking

The first choice is, we just call `server.tick()`, and useless tasks/methods are skipped. This skipping check may cause a waste of time.

The second choice, we can create an interface called `TickStage` for an example, then
```kotlin
class TickEntity: TickStage {
  val currentEntityId: Int

  override fun tick() //...
}
```
and then
```java
TickStage currentStage;

@Overwrite
void tickServer() {
  currentStage.tick()
  if (currentStage.finished()) {
    currentStage = currentStage.next();
  }
}
```
And the question is incompatibility.

**Comment by zly2006** [comment]
Closing because the Tick Stage system is nearly mature, thanks for your discussions!
