### ISSUE TITLE
[Bug]: Scheduled tick undo may cause a mistake because it overwrites other changes.

### ISSUE THREAD

**Issue by zly2006** [zly2006/reden-is-what-we-made#38]
### Please choose if applies:

- [x] I'm currently working on a fix.

### Issue Description

https://github.com/zly2006/reden-is-what-we-made/assets/66198935/103b92f6-eb5f-430c-a240-98de7791699c

### Reproduction

~

### Relevant log output (if applicable)

```Shell
Not applicable
```

### Environment

~

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before
- [X] This is a bug report
- [X] This bug still exists
- [X] I enabled `redenDebug` in carpet or `debugLogger` options in malilib screen for my log

**Comment by zly2006** [comment]
Reason:

For example: suppose there are 3 blocks placed vertically:

```
Water
A (Solid)
B (Solid)
```
if you broke A and B in the same tick, first, A would update water and the water added a scheduled tick, then the water would flown to A, and then B (Note: this is caused by scheduled ticks, so B replaced by water is determined to be caused by breaking A). After that if you press undo, firstly the mod will undo B, then A, but before water flows into B, B is air, so finally it becomes:
```
Water
A (Solid)
B (Air)
```

**Comment by zly2006** [comment]
i think we can add some fields related to time to help determine what B should be when undoing or add a field to save the block state before the water flows into B. but i am not sure.

**Comment by zly2006** [comment]
Solution for:

> ...or add a field to save the block state before the water flows into B. (i.e. `condition`) 

https://github.com/zly2006/reden-is-what-we-made/blob/0232ee66f9e38cda85c697dbb7ff222d735fa420/src/main/java/com/github/zly2006/reden/network/Undo.kt#L39-L47

**Comment by zly2006** [comment]
麻了……这样修不好

想发疯

**Comment by zly2006** [comment]
Add another case:

1. Place a TNT
2. Activate it
3. Place another TNT before it explodes
4. Ctrl+Z twice
5. The new-placed TNT still exists

**Comment by Phoupraw** [comment]
> Reason:
> 
> For example: suppose there are 3 blocks placed vertically:
> 
> ```
> Water
> A (Solid)
> B (Solid)
> ```
> 
> if you broke A and B in the same tick, first, A would update water and the water added a scheduled tick, then the water would flown to A, and then B (Note: this is caused by scheduled ticks, so B replaced by water is determined to be caused by breaking A). After that if you press undo, firstly the mod will undo B, then A, but before water flows into B, B is air, so finally it becomes:
> 
> ```
> Water
> A (Solid)
> B (Air)
> ```

Maybe scheduled ticks should be added into undo list:
- Break A
- Break B
- Water flows into A
- Water flows into B

When undo "break B", water flowing should also be undone.

**Comment by zly2006** [comment]
> 
> Maybe scheduled ticks should be added into undo list:
> 
> * Break A
> * Break B
> * Water flows into A
> * Water flows into B
> 
> When undo "break B", water flowing should also be undone.

Thank you, but still some problems:

1. I have to add a gui or message to let the user know what they are undoing (this is doable, but need to redesign a lot of code)
2. if there are so many scheduled ticks, should i ask players to press Ctrl+Z for each scheduled tick or divide them by time?
3. if the scheduled tick's effects were undone, but the original change tht caused the scheduled tick was not, this may cause some mistake state. e.g. a redstone repeater that never lit with a powered lever behind it. should we warn the player? if so, how?
4. should we add the scheduled tick back in (3) situation or not?

**Comment by Phoupraw** [comment]
> > Maybe scheduled ticks should be added into undo list:
> > 
> > * Break A
> > * Break B
> > * Water flows into A
> > * Water flows into B
> > 
> > When undo "break B", water flowing should also be undone.
> 
> Thank you, but still some problems:
> 
> 1. I have to add a gui or message to let the user know what they are undoing (this is doable, but need to redesign a lot of code)
> 2. if there are so many scheduled ticks, should i ask players to press Ctrl+Z for each scheduled tick or divide them by time?
> 3. if the scheduled tick's effects were undone, but the original change tht caused the scheduled tick was not, this may cause some mistake state. e.g. a redstone repeater that never lit with a powered lever behind it. should we warn the player? if so, how?
> 4. should we add the scheduled tick back in (3) situation or not?

2. pressing ctrl+z only once undo all scheduled ticks after break B, and undo break B
3. scheduled ticks should be re-scheduled after undo
4. yes

**Comment by zly2006** [comment]
> pressing ctrl+z only once undo all scheduled ticks after break B, and undo break B
> scheduled ticks should be re-scheduled after undo
> yes
2. But what about scheduled ticks caused bu scheduled tick?
3&4. if we re-schedule it, then it was ticked, then it made some changes, where should these changes be added to the undo list?

**Comment by Phoupraw** [comment]
> pressing ctrl+z only once undo all scheduled ticks after break B, and undo break B scheduled ticks should be re-scheduled after undo yes
> 2. But what about scheduled ticks caused bu scheduled tick? 3&4. if we re-schedule it, then it was ticked, then it made some changes, where should these changes be added to the undo list?

What's "bu scheduled tick"?

3&4

1. Break A
2. Break B
4. Water flows into A
5. Water flows into B

undo "break B":

1. Break A
2. Water flows into A (re-scheduled)
3. Water flows into B (re-scheduled after "Water flows into A" happened but actually water can't flow into B because B is solid now)

**Comment by zly2006** [comment]
ok, i think it is worth a try
