### ISSUE TITLE
[Bug]: 最新版会导致tis addition注入失败

### ISSUE THREAD

**Issue by 100210110** [zly2006/reden-is-what-we-made#39]
### Please choose if applies:

- [ ] I'm currently working on a fix.

### Issue Description

一次性更新了几个模组到最新版后，无法启动游戏，在这个弹窗里看到reden字样，pcl提示carpet-tis-addition注入失败，把reden回退上一版本就可以进入游戏
![image](https://github.com/zly2006/reden-is-what-we-made/assets/104227884/cbdd0b16-bf72-48cf-930c-bf88b25a5b1c)

### Reproduction

使用fabiric 0.14.22和fabric api 0.90.0后，加入链接内的mod包，把reden替换为最新版（mod包内包含所有mod，包括未启用的旧版reden和启用的新版reden）然后启动游戏，如果不是其他问题的话应该会顺利报错

刚刚注意到了6小时前的0.1.147是更新的版本，尝试后发现同样会造成游戏无法启动，比较新的那份错误报告是属于它的

### Relevant log output (if applicable)

```Shell
链接：https://pan.baidu.com/s/1OOMnr2tiqkPn7nt6k9YZtQ?pwd=1111 
提取码：1111 
--来自百度网盘超级会员V5的分享
```

### Environment

- **Operating System**:Win10 22H2 19045.3570
- **Minecraft Version**:1.20.1
- **Reden Mod Version (or commit number)**:reden-is-what-we-made-0.1.145+50596a0-beta+dev-ci-build.126.jar和reden-is-what-we-made-0.1.147+d53ea70-beta+dev-ci-build.127.jar

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before
- [X] This is a bug report
- [X] This bug still exists
- [X] I enabled `redenDebug` in carpet or `debugLogger` options in malilib screen for my log

**Comment by Qubik65536** [comment]
将整体 log 和 mod 列表直接发送到 GitHub 来

**Comment by zly2006** [comment]
最好log文件上传到github而不是百度网盘，抵制垃圾软件。

您可以将文件拖拽到输入框上传

**Comment by 100210110** [comment]
[错误报告-2023-10-17_2.02.30.zip](https://github.com/zly2006/reden-is-what-we-made/files/12920347/-2023-10-17_2.02.30.zip)
mod包大小为88MB，超过了25MB的限制，分卷压缩了，请把01234的后缀zip删掉，使用度盘为工作上的习惯，抵制垃圾软件
![image](https://github.com/zly2006/reden-is-what-we-made/assets/104227884/e9864377-04a4-4fc5-ad0d-801c99bf3894)

[mods.zip](https://github.com/zly2006/reden-is-what-we-made/files/12920424/mods.zip)
[mods.z01.zip](https://github.com/zly2006/reden-is-what-we-made/files/12920403/mods.z01.zip)
[mods.z02.zip](https://github.com/zly2006/reden-is-what-we-made/files/12920404/mods.z02.zip)
[mods.z03.zip](https://github.com/zly2006/reden-is-what-we-made/files/12920405/mods.z03.zip)
[mods.z04.zip](https://github.com/zly2006/reden-is-what-we-made/files/12920406/mods.z04.zip)

**Comment by zly2006** [comment]
modlist不是mod包，上传完整log就行，想测试我们会自己下载这些mod

错误报告已经包含了log，发那个就够了

**Comment by zly2006** [comment]
有点麻烦，要不让tis他们那边改吧

他们的注入点本来就不太对

```java
// carpettisaddition.mixins.rule.chunkTickSpeed.ServerWorldMixin
    @Inject(
        method = {"tick"},
        at = {@At(
    value = "INVOKE",
    target = "Lnet/minecraft/server/world/ServerWorld;getChunkManager()Lnet/minecraft/server/world/ServerChunkManager;"
)}
    )
    void resetTickChunkDepth(BooleanSupplier shouldKeepTicking, CallbackInfo ci) {
        this.depth = 0;
    }
```
建议改成：`Lnet/minecraft/world/chunk/ChunkManager;tick(Ljava/util/function/BooleanSupplier;Z)V`

**Comment by zly2006** [comment]
可以确认修改后不会发生兼容性bug
