### ISSUE TITLE
[功能请求]: Reden Profiler

### ISSUE THREAD

**Issue by zly2006** [zly2006/reden-is-what-we-made#40]
### 请选择：

- [X] 我正在着手增加这个功能

### 描述您想要的解决方案

计划做一个更好的profiler，集成化机器的性能测试，自动帮你测试机器并生成测试报告。

欢迎大家在下面留言要收集的数据，提出建议，包括：
+ 你要收集什么信息？（比如：mspr）
+ 怎么展示信息？（比图：图表）

也可以给出更有趣的功能，比如：
+ 告诉你哪些地方最卡
+ 告诉你哪里的卡顿高于以往测试的平均值（也就是还有很大优化空间）
+ ……

一切正在起步，积极参与讨论可以帮助项目更快实现！

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by wendavid552** [comment]
可以考虑在[Observable](https://github.com/tasgon/observable)基础上增加功能，Observable支持查看每种红石原件的卡顿占比等等；或者Spark的报告生成，还能包括如gc和mspt曲线等等功能。主要是这个报告可能会有很多专业性的问题，例如计时的准确性，不过确实有助于看代码找lag。

**Comment by zly2006** [comment]
很遗憾此需求由于开发时间不够将被废弃
