### ISSUE TITLE
[功能请求]: 客户端高亮功能的提议

### ISSUE THREAD

**Issue by stjak123** [zly2006/reden-is-what-we-made#45]
### 请选择：

- [ ] 我正在着手增加这个功能

### 描述您想要的解决方案

**允许客户端高亮白名单内实体**
通过热键触发高亮指定白名单内实体

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by zly2006** [comment]
hotkey?

现在写的是
`/glow @e[type=panda]`
`/glow @a`
`/glow clear`
这样的

**Comment by stjak123** [comment]
指令触发也没问题的,我认为添加热键后可能会更方便一些
如果认为没有必要的话当前的状态已经足够了

**Comment by zly2006** [comment]
> 指令触发也没问题的,我认为添加热键后可能会更方便一些 如果认为没有必要的话当前的状态已经足够了

添加热键的话，操作和作用是什么

**Comment by stjak123** [comment]
允许用户创建一个或多个白名单 触发热键后开启或关闭制定白名单内实体的高亮效果
或是一键高亮所有生物 类似这种的功能

**Comment by zly2006** [comment]
> 触发热键后开启或关闭制定白名单内实体的高亮效果

这个可以有

> 一键高亮所有生物

`/glow @e`即可
