### ISSUE TITLE
[Bug]: Command hotkeys are not applied correctly.

### ISSUE THREAD

**Issue by zly2006** [zly2006/reden-is-what-we-made#46]
### Please choose if applies:

- [ ] I'm currently working on a fix.

### Issue Description

Super Right -> runCommands

@wafarm 

### Reproduction

1. Modify command list in the command hotkey config. Note: DO NOT add or remove a command, e.g. /say command
2. Press the hotkeys
3. The old command was executed

### Relevant log output (if applicable)

```Shell
~
```

### Environment

Reden: 0.1.238+2ebd994-dev

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before
- [X] This is a bug report
- [X] This bug still exists
- [X] I enabled `redenDebug` in carpet or `debugLogger` options in malilib screen for my log

**Comment by zly2006** [comment]
https://github.com/zly2006/reden-is-what-we-made/blob/7485380e0ac17126f2204960b2798f2ff7450a4a/src/main/java/com/github/zly2006/reden/malilib/gui/GuiCommandHotkeyListEdit.kt#L64-L71

is this code still needed? it seems will never be called @wafarm

**Comment by wafarm** [comment]
> https://github.com/zly2006/reden-is-what-we-made/blob/7485380e0ac17126f2204960b2798f2ff7450a4a/src/main/java/com/github/zly2006/reden/malilib/gui/GuiCommandHotkeyListEdit.kt#L64-L71
> 
> is this code still needed? it seems will never be called @wafarm

`removed` should be a function of the `Screen` class. Minecraft will call this function when a screen is removed. We need to update configs when that happens.

**Comment by zly2006** [comment]
> `removed` should be a function of the `Screen` class. Minecraft will call this function when a screen is removed. We need to update configs when that happens.

yes but i added a logger in this method and nothing logged when i close the screen :confused:

**Comment by wafarm** [comment]
idk then. Maybe it's an issue related to malilib.

**Comment by zly2006** [comment]
well, then just leave it.
