### ISSUE TITLE
[Bug]: 刷怪蛋生成幼年生物无法撤回

### ISSUE THREAD

**Issue by stjak123** [zly2006/reden-is-what-we-made#48]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

当使用刷怪蛋对着对应生物右键时，会生成对应幼年生物。该操作无法被撤回。

### 重现

1 安装reden 0.1.243及其前置mod
2 安装上述步骤操作

### 环境

- **操作系统**：Linux (aarch64) version Android-11
- **Minecraft 版本**：1.20.1
- **Reden Mod 版本（或 commit SHA）：**：0.1.243

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在
- [x] 我在carpet中启用了`redenDebug`选项或在malilib配置中启用了`debugLogger`选项

**Comment by zly2006** [comment]
原因是没注入use entity
