### ISSUE TITLE
[Bug]: Undo books on a chiseled bookshelf may cause a mistake

### ISSUE THREAD

**Issue by stjak123** [zly2006/reden-is-what-we-made#51]
### Please choose if applies:

- [ ] I'm currently working on a fix.

### Issue Description

**Undo a book(books) that has already been placed on the bookshelf** Place a new book at this point will cause the previous one to reappear. 
**Undo a book that has been taken out:** This will result in a book that cannot be taken out.
_These erroneous books can be detected using a comparator. Books of the first scenario can be taken out normally,they also have normal drops,but the second scenario doesn't have these._

### Reproduction

_Follow the above steps with reden-0.1.275_

### Relevant log output (if applicable)

```Shell
~
```

### Environment

- **Operating System**:Linux (aarch64) version Android-11
- **Minecraft Version**:1.20.1
- **Reden Mod Version (or commit number)**:0.1.275

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before
- [X] This is a bug report
- [X] This bug still exists
- [X] I enabled `redenDebug` in carpet or `debugLogger` options in malilib screen for my log

**Comment by zly2006** [comment]
能否提供一段录屏？

**Comment by stjak123** [comment]
[Uploading vd.zip…]()

**Comment by zly2006** [comment]
Please test in the new version.

**Comment by stjak123** [comment]
fixed
thanks for your work
