### ISSUE TITLE
[Bug]: Failed to undo the modification of the monster spawner and sign

### ISSUE THREAD

**Issue by stjak123** [zly2006/reden-is-what-we-made#52]
### Please choose if applies:

- [ ] I'm currently working on a fix.

### Issue Description

**The use of spawn eggs in the monster spawner cannot be undone:** Using spawn eggs to set or change the generated mobs in the monster spawner cannot be undone.
**Waxing or dyeing of signs cannot be undone:** Modifying signs (or hanging signs) with honey wax or dye cannot be undone.

### Reproduction

~

### Relevant log output (if applicable)

```Shell
~
```

### Environment

**Operating System:** Linux (aarch64) version Android-11
**Minecraft Version**: 1.20.1
**Reden Mod Version:** 0.1.275

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before
- [X] This is a bug report
- [X] This bug still exists
- [X] I enabled `redenDebug` in carpet or `debugLogger` options in malilib screen for my log

**Comment by zly2006** [comment]
i think modifying signs does not matter, it just make the code more complex and players hardly use that feature.

for mob spawners, i am working on a fix now.

**Comment by zly2006** [comment]
Please test in the newest version, if the bug still exists, please reopen this issue.

**Comment by stjak123** [comment]
If there was another monster inside earlier, undoing will result in an error
_Besides,i cannot reopen a issue which closed by u_
