### ISSUE TITLE
[Bug]: reden无法撤销动物繁殖

### ISSUE THREAD

**Issue by alittlehuaji** [zly2006/reden-is-what-we-made#56]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

无法撤销繁殖出来的生物

### 重现

https://github.com/zly2006/reden-is-what-we-made/assets/119058504/3011c7e5-dcef-4b1a-a9e4-7cde2bc3bd1e

### 环境

- **Windows 11 23H2**：
- **1.20.1**：
- **0.1.304+d75d165**：

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在
- [X] 我在carpet中启用了`redenDebug`选项或在malilib配置中启用了`debugLogger`选项

**Comment by zly2006** [comment]
请提供日志，reden-debug.log

**Comment by alittlehuaji** [comment]
[reden-debug.zip](https://github.com/zly2006/reden-is-what-we-made/files/13529832/reden-debug.zip)

**Comment by zly2006** [comment]
显然这已经脱离了红石机器的范畴
