### ISSUE TITLE
[功能请求]: 撤销方块更新开关

### ISSUE THREAD

**Issue by ww2e** [zly2006/reden-is-what-we-made#57]
### 请选择：

- [ ] 我正在着手增加这个功能

### 描述您想要的解决方案

为撤销增加是否方块更新开关

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定没有人提交过与此功能请求相关的 issue

**Comment by zly2006** [comment]
请详细说明你到底要什么样的新功能，包括原理、触发方式、UI或者feedback、为什么需要、使用场景举例等方面。

**Comment by ww2e** [comment]
原理:在撤销时触发方块更新
触发方式:Reden配置>通用增加一个按钮,叫撤销的方块更新
为什么需要:有的时候撤销时无更新可能会导致机器运行不正常(如活塞接高频侦测器在撤销开启时不会高频)

**Comment by zly2006** [comment]
不懂就问，真的有人需要这个功能吗？

**Comment by ww2e** [comment]
是我的错,我是傻逼,抱歉

**Comment by stjak123** [comment]
我认为增加此类功能可能导致撤销时产生无法预料的后果
并且我认为 此功能可以通过类似"tick frezze后手动将上次操作造成的改变放回去"实现同样的效果。
再者，这么做会产生新的更新而导致陷入**重复撤销的循环**。
即使有办法不产生新的undo记录，也会导致包括但不限于因需要撤回的方块产生更新导致不当的bud态被破坏,侦测器被不当激活等后果,并且因为没有undo记录,从而导致"此次撤回导致的后果"是无法撤回的。
但虽然此功能实用性低,但如果实现不复杂的话或许可以作为一个debug功能加入?

**Comment by zly2006** [comment]
Link to #97

此issue所指应该是特制的setBlockNoPP导致了bug，所以直接移除此方法应该能解决此问题

**Comment by zly2006** [comment]
@stjak123 @ww2e   请描述你们遇到的具体问题，然后确认是否还存在。

fixed in bf198b6e,

**Comment by zly2006** [comment]
Closing due to no response so long, if you found this causes a bug please open a new issue. Thanks.
