### ISSUE TITLE
[Bug]: 服务器中撤销压线红石信号错误

### ISSUE THREAD

**Issue by ww2e** [zly2006/reden-is-what-we-made#59]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

我在服务器中摆放了一个压线结构,撤销压线时发现后端红石信号保持不变

### 重现

1.加入一个服务器.
2.摆出如下方块形状:
![image](https://github.com/zly2006/reden-is-what-we-made/assets/103339776/b123e0fc-7118-4d2d-a715-a372aae0de9e)
3.在14信号强度红石粉的上方摆放固体方块,使其压线
![image](https://github.com/zly2006/reden-is-what-we-made/assets/103339776/f71813d9-1e2c-4e7c-9ef3-2a9c9663ce95)
4.撤销刚才的操作,bug产生,原14,13信号强度处红石粉的红石信号强度仍然和压线时一样.
![image](https://github.com/zly2006/reden-is-what-we-made/assets/103339776/1c07ba26-9008-49bd-a855-d3876d9f4688)

### 相关日志输出（如果有）

```Shell
事实上,由于另一个bug的存在,无法提供日志.
```

### 环境

- **操作系统**：windows11家庭版
- **Minecraft 版本**：1.20.1
- **Reden Mod 版本（或 commit SHA）：**：modrinth最新版(当前) Reden Pre-Release 0.1.304+d75d165.github.ci.268

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在
- [X] 我在carpet中启用了`redenDebug`选项或在malilib配置中启用了`debugLogger`选项

**Comment by zly2006** [comment]
latest.log

**Comment by zly2006** [comment]
复现失败，请检查模组兼容性，一出其他模组后重试
