### ISSUE TITLE
Bukkit based server support

### ISSUE THREAD

**Issue by s-yh-china** [zly2006/reden-is-what-we-made#6]
Link to LeavesMC/Leaves#111

**Comment by zly2006** [comment]
首先是不计划支持bukkit的——很多功能bukkit api做不到，只能依靠你的leaves改源码实现

其次rvc还未设计完成，不建议过早实现支持

**Comment by zly2006** [comment]
undo redo实际上就一个包，相对比较稳定

**Comment by s-yh-china** [comment]
bukkit下游的很多机制都很奇怪 我也不敢保证能做成什么样XD

**Comment by zly2006** [comment]
考虑到reden这边的undo & redo功能基本稳定（代码也不算多，see`UpdateMonitorHelper`），总之如果LeavesMC愿意实现的话，欢迎新开issue或者用其他方式提问。Bukkit server将**不会**是本项目的一部分，故关闭此issue。
