### ISSUE TITLE
[Bug]: 服务器中关于reden调试日志的四个异常

### ISSUE THREAD

**Issue by ww2e** [zly2006/reden-is-what-we-made#60]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

当我在服务器中输入指令/carpet redenDebug true开启调试后,显示如下报错信息:
![image](https://github.com/zly2006/reden-is-what-we-made/assets/103339776/15f5eb81-9969-4060-9bee-3eaf20d10995)
关闭时显示如下异常信息:
![image](https://github.com/zly2006/reden-is-what-we-made/assets/103339776/5d84d581-9d8f-4c3e-902a-2a9bf9307b22)
但再次输入指令即可关闭.
在开启时无法放置方块与修改方块状态(类似于Minecraft插件中的事件被取消)
并且无法获取到日志.

### 重现

在服务器中输入指令/carpet redenDebug true开启调试
出现bug

### 相关日志输出（如果有）

```Shell
实际上,由于这个bug,我无法获取到日志
```

### 环境

- **操作系统**：windows11 家庭版
- **Minecraft 版本**：1.20.1
- **Reden Mod 版本（或 commit SHA）：**：modrinth上的最新版本(当前) Reden Pre-Release 0.1.304+d75d165.github.ci.268

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在
- [X] 我在carpet中启用了`redenDebug`选项或在malilib配置中启用了`debugLogger`选项

**Comment by zly2006** [comment]
latest.log日志有吗

**Comment by zly2006** [comment]
fixed
