### ISSUE TITLE
[Bug]: 雕文书架重复撤回引发的错误

### ISSUE THREAD

**Issue by stjak123** [zly2006/reden-is-what-we-made#61]
### 请选择：

- [ ] 我正在着手修复这个问题

### 问题描述

在雕文书架中放入一本书(book_A)
放入另一本书(book_B)
撤回上一次操作(undo book_B)
再次放入一本书(book_C)
撤回上一次操作(undo book_C)
再次放入一本书(book_D)
此时 第一本书(book_A)在放入的同时消失

### 重现

同上

### 环境

- **操作系统**：Windows11
- **Minecraft 版本**：1.20.1
- **Reden Mod 版本（或 commit SHA）：**：665f6a7

### 请确认以下条款

- [X] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在
- [X] 我在carpet中启用了`redenDebug`选项或在malilib配置中启用了`debugLogger`选项

**Comment by zly2006** [comment]
please test the newest ci build.

**Comment by stjak123** [comment]
前版本修复的bug重新出现
-放入book_A
-撤回
-放入book_B
此时book_A错误的出现

**Comment by stjak123** [comment]
即
被撤回的书仅在外观上被撤回 实际上无论从掉落物 红石比较器检测该书还是存在的

**Comment by zly2006** [comment]
> please test the newest ci build.

这个bug在最新版还存在吗？

**Comment by zly2006** [comment]
由于长时间没有回复，关闭此issue
