### ISSUE TITLE
[Feature Request]: Implement basic JGit architecture and feature

### ISSUE THREAD

**Issue by Qubik65536** [zly2006/reden-is-what-we-made#62]
### Please choose if applies:

- [ ] I'm currently working on adding this feature.

### Describe the solution you'd like

Implement basic JGit architecture and feature so other modules in the mod can use features provided by JGit.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/zly2006/reden-is-what-we-made/issues) and this has not been posted before

**Comment by zly2006** [comment]
Is it something like `git init` and `git commit` `pull` `push`(without branches) ? or something more like `git diff`? or `rebese` `merge` that looks like a full version control system?

**Comment by Qubik65536** [comment]
> Is it something like `git init` and `git commit` `pull` `push`(without branches) ? or something more like `git diff`? or `rebese` `merge` that looks like a full version control system?

Ideally all of them being capable of operating serialized plain text files.

All the other operations like in-game UI to operate RVC feature (to commit, solve conflict, etc.) aren't in the scope of this issue (and the following PR).

**Comment by zly2006** [comment]
link to #25, if this issue is completed, it should be closed as well.

**Comment by Qubik65536** [comment]
> link to #25, if this issue is completed, it should be closed as well.

No it shouldn't.

> All the other operations like in-game UI to operate RVC feature (to commit, solve conflict, etc.) **AREN'T** in the scope of this issue (and the following PR).
