### ISSUE TITLE
[COMMUNITY]: Add code of conduct and contribution/style guide

### ISSUE THREAD

**Issue by Qubik65536** [zly2006/reden-is-what-we-made#80]
Add a **code of conduct** and and contribution style guide (for both documentations and codes) for both the main project and the [undo hard fork](https://github.com/RedenMC/undo).

**Comment by zly2006** [comment]
我认为在code of conduct之前先讨论一下是否应该把禁用模组中的功能（封禁玩家/封ip）作为合适的社区治理手段？

首先是人们可能的反感
还有reden api后台也需要更多的开发工作了

**Comment by Qubik65536** [comment]
> 我认为在code of conduct之前先讨论一下是否应该把禁用模组中的功能（封禁玩家/封ip）作为合适的社区治理手段？
> 
> 首先是人们可能的反感 还有reden api后台也需要更多的开发工作了

CODE OF CONDUCT 只包含代码与文档社区工作相关内容，这类应该属于 mod 本身软件的 TOS，不在本 issue 范畴内

**Comment by zly2006** [comment]
sad
