### ISSUE TITLE
SuperRight中仅能设置9组命令

### ISSUE THREAD

**Issue by Zeratul-cn** [zly2006/reden-is-what-we-made#9]
命令链转化成快捷键是个很好的想法，希望能够把数量弄成自定义的（9个真的是挺少的）

**Comment by zly2006** [comment]
主要是太麻烦了，要不多添加一些槽位？

本来就是一个很小的功能，没必要浪费时间

**Comment by Zeratul-cn** [comment]
多些槽位也不错，能把一些carpet特别常用的指令，比方说/tick freeze /player 化成快捷键也足够了

**Comment by zly2006** [comment]
你觉得多少是合理的？
