### ISSUE TITLE
[Bug]: Windows系统下无法直接删除RVC Repo

### ISSUE THREAD

**Issue by SkyDynamic** [zly2006/reden-is-what-we-made#90]
### 请选择：

- [X] 我正在着手修复这个问题

### 问题描述

在Windows系统下，若程序占用文件时，另外的程序操作该文件，会抛出权限不足。

在我尝试删除RVC repo时，MC崩溃，查看日志后发现由于权限不足无法删除`.git`文件夹

### 重现

1. git pull 并更新到最新版本
2. ./gradlew build 或 直接IDEA Launch
3. 随便导入或新建一个RVC
4. 删除RVC

### 相关日志输出（如果有）

```Shell
log: https://pastebin.com/1f1kFQDb
```

### 环境

- **操作系统**：Windows 11
- **Minecraft 版本**：1.20.4
- **Reden Mod 版本（或 commit SHA）：**：3b846a73b83f3a884be9fcea8671c2d9187f7928

### 请确认以下条款

- [x] 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定我提交的问题并没有重复
- [X] 本 issue 是 bug 反馈
- [X] 本 bug 在最新版本中仍存在
- [X] 我在carpet中启用了`redenDebug`选项或在malilib配置中启用了`debugLogger`选项

**Comment by zly2006** [comment]
在delete之前已经对git repository执行了close，目前还不知道为啥还在占用

https://github.com/zly2006/reden-is-what-we-made/blob/99d6fdc1fcb922ba8f309c3cc57b4f6781f99da5/src/main/java/com/github/zly2006/reden/rvc/tracking/RvcRepository.kt#L134-L140
